# Generated by Django 4.2.9 on 2025-03-16 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bay_bed_variety_weekentry_dataentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
