# Generated by Django 4.2.9 on 2025-03-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bay',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
